//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int Id { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string No { get; set; }
        public Nullable<System.DateTime> DatePayment { get; set; }
        public Nullable<int> TypePayment { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> PriceId { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> BonusMonth { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual MyCompany MyCompany { get; set; }
    }
}
