//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSign
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> UserCreate { get; set; }
        public string SenderName { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> CurrentStep { get; set; }
        public Nullable<bool> MyselfSign { get; set; }
    }
}
