//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailServer
    {
        public int Id { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> AutoSendEmail { get; set; }
        public Nullable<bool> MethodSendSSL { get; set; }
        public string SMTPServer { get; set; }
        public Nullable<int> Port { get; set; }
        public string EmailServer1 { get; set; }
        public string Password { get; set; }
    }
}
