//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailActiveFileAttach
    {
        public int Id { get; set; }
        public Nullable<int> EmailActiveId { get; set; }
        public string FullPathFileAttach { get; set; }
        public string FileName { get; set; }
    
        public virtual EmailActive EmailActive { get; set; }
    }
}
