//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSign
    {
        public int Id { get; set; }
        public Nullable<int> DocumentSingId { get; set; }
        public Nullable<int> ThreadedSignDocumentId { get; set; }
        public Nullable<int> OrderSign { get; set; }
    }
}
