//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSignDetail
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeSignId { get; set; }
        public Nullable<int> FileSignId { get; set; }
        public Nullable<int> SignType { get; set; }
        public Nullable<int> Page { get; set; }
        public Nullable<decimal> CoordinateX { get; set; }
        public Nullable<decimal> CoordinateY { get; set; }
        public Nullable<decimal> Scale { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> OrderLink { get; set; }
    }
}
