//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileSign
    {
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DocumentSignId { get; set; }
        public Nullable<int> UserUpload { get; set; }
        public string FileSourceType { get; set; }
        public string FileConvertType { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FileConvert { get; set; }
        public Nullable<int> NumberPage { get; set; }
        public Nullable<int> Orders { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> Status { get; set; }
        public string FileNameSave { get; set; }
    }
}
