//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfig
    {
        public int Id { get; set; }
        public string FilePathToken { get; set; }
        public string PassWord { get; set; }
        public string IVANCode { get; set; }
        public string IVANName { get; set; }
        public string IVANPass { get; set; }
        public string ModeSign { get; set; }
    }
}
