//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Data.DBAccessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.LoginUsers = new HashSet<LoginUser>();
            this.UserRoleDetails = new HashSet<UserRoleDetail>();
        }
    
        public int UserRoleSID { get; set; }
        public string Levels { get; set; }
        public string RoleName { get; set; }
        public string DefaultPage { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<LoginUser> LoginUsers { get; set; }
        public virtual ICollection<UserRoleDetail> UserRoleDetails { get; set; }
    }
}
